### ISSUE TITLE
Can't log in to osjs

### ISSUE THREAD

**Issue by craig-mulligan** [Agile-IoT/agile-stack#31]
Navigating to `:8000` this directs me to `idm` which prompts me for a login, but this fails with: 

<img width="1139" alt="screen shot 2017-08-03 at 12 45 22" src="https://user-images.githubusercontent.com/9499917/28920456-dbfdbfd4-7849-11e7-87da-14bc541397f5.png">

Cc @nopbyte

**Comment by craig-mulligan** [comment]
Do I have to create a user before hand somehow?

**Comment by nopbyte** [comment]
Hi @craig-mulligan,

This should be working. Did you try the user referenced in the documentation in the "Access to the AGILE Web UI"  section of the documentation 

http://agile-iot.eu/wiki/index.php?title=Getting_started_with_AGILE

If you want to be safe, you can remove the idm folder mounted from the docker-compose file in your host, to make IDM recreate the entities and copy the latests configuration.  

Also, it would be helpful if you can check the logs from the security container after it boots. It should give you some info about whether it was possible to create the admin user or not. 

You should see something like " SUCCESS: User created agile!@!agile-local" for the first time that you boot the container (with a clean configuration and database folder). Otherwise it will say that it was not possible to create the user because it is already there.

**Comment by craig-mulligan** [comment]
Ah I see, I thought we could create an new user on a new provision, I'll try again with those credentials and report back.

**Comment by craig-mulligan** [comment]
Worked.
